version: "2"

volumes:
  db_data:
    driver: local
  gem_data:
    driver: local
  node_modules_data:
    driver: local

services:
  rails:
    build:
      dockerfile: containers/dev/rails/Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - gem_data:/usr/src/app/vendor/bundle
      - node_modules_data:/usr/src/app/node_modules
    environment:
      RAILS_ENV : development
      DB_HOSTNAME : db
      MANUAL: $MANUAL
    command: bin/docker_compose_startup_wrapper.sh
    depends_on:
      - db
  db:
    build: containers/dev/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE : sample_development
      MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
    volumes:
      - db_data:/var/lib/mysql

