default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: <%= ENV.fetch('DB_HOSTNAME') { '127.0.0.1' } %>
  database: sample_development

test:
  <<: *default
  host: <%= ENV.fetch('DB_HOSTNAME') { '127.0.0.1' } %>
  database: sample_test

production:
  <<: *default
  host: <%= ENV.fetch('DB_HOSTNAME') { '127.0.0.1' } %>
  database: sample_production
